### ISSUE TITLE
Failed to activate the todo package

### ISSUE THREAD

**Issue by nilforooshan** [reergymerej/todo#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [todo](https://github.com/reergymerej/todo) package 0.6.0

### Stack Trace

Failed to activate the todo package

```
At Cannot find module 'react'

Error: Cannot find module 'react'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:145974)
    at Object.<anonymous> (~/Downloads/Atom_packages/todo/lib/todo-view.js:11:14)
    at /packages/todo/lib/todo-view.js:110:24)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:145974)
    at /packages/todo/lib/todo.js:5:32)
    at /packages/todo/lib/todo.js:98:20)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:1:626990)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3039740)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:3027874)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:14:1717)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1192024)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349490)
```

### Commands

```
     -0:11.8.0 todo:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-language-r 1.4.8 
highlight-selected 0.14.0 
todo 0.6.0 
```

**Comment by reergymerej** [comment]
I’ll check on it. Thank you for the ticket.
